# Generated by Django 3.1.4 on 2020-12-26 13:13

import ckeditor.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Slug', models.SlugField(unique=True)),
                ('Category', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Action', 'Action'), ('Animation', 'Animation'), ('Documentary', 'Documentary'), ('Fantasy', 'Fantasy'), ('Music', 'Music'), ('Sci-Fi', 'Sci-Fi'), ('Tv Movie', 'Tv Movie'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('History', 'History'), ('Mystery', 'Mystery'), ('Science-Fiction', 'Science-Fiction'), ('War', 'War'), ('Crime', 'Crime'), ('Family', 'Family'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Western', 'Western')], max_length=162, null=True)),
                ('Description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Img', models.ImageField(upload_to='pics')),
                ('link1', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
