# Generated by Django 3.1.4 on 2020-12-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='Release',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='Views',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
