# Generated by Django 3.1.4 on 2020-12-26 17:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0002_auto_20201226_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='Category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Action', 'Action'), ('Animation', 'Animation'), ('Adventure', 'Adventure'), ('Crime', 'Crime'), ('Comedy', 'Comedy'), ('Documentary', 'Documentary'), ('Drama', 'Drama'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('History', 'History'), ('Music', 'Music'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Science-Fiction', 'Science-Fiction'), ('Tv Movie', 'Tv Movie'), ('Thriller', 'Thriller'), ('War', 'War'), ('Western', 'Western')], max_length=162, null=True),
        ),
    ]
