# Generated by Django 3.1.4 on 2020-12-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0004_auto_20201227_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='Views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
