# Generated by Django 3.1.4 on 2020-12-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0005_auto_20201227_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='Views',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
