# Generated by Django 3.1.4 on 2020-12-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0008_auto_20201227_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='link1',
            new_name='URL',
        ),
        migrations.RemoveField(
            model_name='film',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='film',
            name='Img',
        ),
        migrations.AddField(
            model_name='film',
            name='Genre',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='Image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
